name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
            distribution: 'adopt'
            java-version: '12.x'
      - uses: nazriarwadi/Apk_BankSampah@v1
        with:
            channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
